In [51]:
import numpy as np

print()
print()
print()
print()

twod = np.array([[1,2,3],[1,3,6],[1,2,3]])
print(twod)
print(twod.shape)
print(twod[1][2])

threedarray = np.array([[[1,2,3],[4,5,6]],
                        [[7,8,9],[10,11,12]],
                        [[13,14,15],[16,17,18]]])
print("value is ",threedarray[2,1,0])
print(threedarray.shape)
transform = threedarray.T
print(transform)

value = threedarray[0,0]

print(f"value", value)

print(threedarray)






[[1 2 3]
 [1 3 6]
 [1 2 3]]
(3, 3)
6
value is  16
(3, 2, 3)
[[[ 1  7 13]
  [ 4 10 16]]

 [[ 2  8 14]
  [ 5 11 17]]

 [[ 3  9 15]
  [ 6 12 18]]]
value [1 2 3]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
