In [2]:
!pip3 install pandas
import pandas as pd

Defaulting to user installation because normal site-packages is not writeable
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 28.6 MB/s  0:00:00m0:00:010:01
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]


In [3]:
import pandas as pd

In [4]:
pd.Series([96.9,78.5,50.4,34.9,12.8])

0    96.9
1    78.5
2    50.4
3    34.9
4    12.8
dtype: float64

In [5]:
pd.Series([96.9,78.5,50.4,34.9,12.8],index = ["Alice","Bob","Charlie","Diana","Smith"])

Alice      96.9
Bob        78.5
Charlie    50.4
Diana      34.9
Smith      12.8
dtype: float64

In [6]:
pd.Series([96.9,78.5,50.4,34.9,12.8],index = ["Alice","Bob","Charlie","Diana","Smith"])

data = {"Alice":96.9,"Bob":78.5,"Charlie":50.4,"Diana":34.9,"Smith":12.8}

In [7]:
data

{'Alice': 96.9, 'Bob': 78.5, 'Charlie': 50.4, 'Diana': 34.9, 'Smith': 12.8}

In [8]:
pd.Series(data)

Alice      96.9
Bob        78.5
Charlie    50.4
Diana      34.9
Smith      12.8
dtype: float64

In [9]:
 scores = pd.Series(data)

In [10]:
scores

Alice      96.9
Bob        78.5
Charlie    50.4
Diana      34.9
Smith      12.8
dtype: float64

In [11]:
scores.values

array([96.9, 78.5, 50.4, 34.9, 12.8])

In [15]:
  sum = scores.values.sum

In [16]:
sum

<function ndarray.sum>

In [21]:
scores = pd.Series([96.9,78.5,50.4,34.9,12.8])
scores.sum()

np.float64(273.5)

In [22]:
scores.mean()

np.float64(54.7)

In [23]:
scores.median()

np.float64(50.4)

In [24]:
scores.min()

np.float64(12.8)

In [25]:
scores.max()

np.float64(96.9)

In [26]:
scores.values *2

array([193.8, 157. , 100.8,  69.8,  25.6])

In [27]:
scores.values > 50

array([ True,  True,  True, False, False])

In [28]:
pd.Series(scores,name = "Exam scores")

0    96.9
1    78.5
2    50.4
3    34.9
4    12.8
Name: Exam scores, dtype: float64